ALTER TABLE "ScamReport" ADD COLUMN "urlHash" TEXT NOT NULL DEFAULT '';
ALTER TABLE "ScamReport" ADD COLUMN "count" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "ScamReport" ADD COLUMN "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX "ScamReport_urlHash_idx" ON "ScamReport"("urlHash");
