CREATE TABLE IF NOT EXISTS "ScamReport" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "verdict" TEXT NOT NULL,
  "score" INTEGER NOT NULL,
  "scamType" TEXT,
  "note" TEXT,
  "urls" TEXT NOT NULL
);
